### ISSUE TITLE
Show transaction fees on TX Detail page

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#124]
## Story

As a user, I want to view the transaction fees for a given transaction, so I can better understand my costs and NEAR's economics.

## Acceptance Criteria

- [x] Total Gas Cost (gas used * gas price)
- [x] Gas Units Used (units of gas)
- [x] Gas Unit Price (price per unit in NEAR) Ⓝ

**Comment by frol** [comment]
Fees are not exposed via RPC for individual transactions just yet (https://github.com/nearprotocol/nearcore/issues/1299), so this issue is blocked by nearcore.

**Comment by icerove** [comment]
got it

**Comment by icerove** [comment]
https://github.com/nearprotocol/nearcore/pull/2109

**Comment by frol** [comment]
@icerove Why exactly are we waiting for nearprotocol/nearcore#2109?

It seems that this issue is only blocked by https://github.com/nearprotocol/nearlib/issues/242

**Comment by icerove** [comment]
I think gas price can be extracted from block header we already have

**Comment by frol** [comment]
We can do that as well, but pushing nearlib is not that hard as well.

**Comment by icerove** [comment]
Definitely can, but it will be slower since we go into nearlib and wait for query again to get gas price. Does not make more sense to do so. Still do the work to expose gas price in the nearlib

**Comment by frol** [comment]
It is unclear why do you think we already have information about a block header on the transaction details page.
