### ISSUE TITLE
[Suggestion] show --account-id as required in near CLI help

### ISSUE THREAD

**Issue by sweetpotatoz** [nearprotocol/near-explorer#125]
## Story
near tx-status
does not show --accountId as [required]

but in fact, it is a required parameter for near tx-status to work properly

## Acceptance Criteria

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockup: 

## NOTES

-

**Comment by frol** [comment]
near CLI is near-shell project on github, so here is the issue: https://github.com/nearprotocol/near-shell/issues/187
