### ISSUE TITLE
Expose new Telemetry data

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#128]
## Story

As a chain developer who uses Nodes page, I want to see detailed information about nodes running the network so I can get a better idea about what is going on.

Nearcore is going to update the Telemetry format (https://github.com/nearprotocol/nearcore/pull/1751), so it is going to be:

```json
{
  "agent": {
    "name": "near-rs",
    "version": "0.4.5",
    "build": "6a527109-modified"
  },
  "chain": {
    "node_id": "ed25519:67U1Mup5E98t5fQTJvpMuS7bq8rYDmyqWjeQ5884LHH7",
    "status": "NoSync",
    "account_id": "test.near",
    "num_peers": 0,
    "is_validator": true,
    "latest_block_hash": "7a4d3SNNb1XGxqhHAKj5nGx8C1R4X8pdt8jobC9z3nup",
    "latest_block_height": 1889
  },
  "signature": "ed25519:4n5VzXijHUvgwroD1W6BTysRGKTMdPv6ks32kEUNGyb9recDYRpt2L8Y2Uq5ABPt4LZHFBAv2DPj1CAPGkwqkZg2",
  "system": {
    "bandwidth_download": 0,
    "bandwidth_upload": 0,
    "cpu_usage": 0.6015791296958923,
    "memory_usage": 42784
  }
}
```

So, the data is going to be split into three sections now (agent [info about the running binary], system [info about the system load], chain), and the only new data here is the "agent" section.

## Acceptance Criteria

- [x] Accept the new Telemetry format while keeping compatibility with the old one for a little while
- [ ] Display the new information (`chain.is_validator`, `agent.*`) in the UI
- [ ] Mobile ok
- [ ] Tested

## Designs

https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=186%3A15

## Notes

Nearcore sends Telemetry data as JSON with `POST` request to `/api/nodes`, which is [handled by Next.js and passed with an extra `ip_address` information to the backend](https://github.com/nearprotocol/near-explorer/blob/5ab5c54fe0e98a8fa4128720cc5537754526a3ca/frontend/src/pages/api/nodes.js), where [it is saved to the database](https://github.com/nearprotocol/near-explorer/blob/5ab5c54fe0e98a8fa4128720cc5537754526a3ca/backend/src/wamp.js#L14-L24). A lot of information is currently ignored, so we should add more columns or JSON column to store all the information.

The current ("old") Telemetry format is:

```json
{
  "node_id": "ed25519:67U1Mup5E98t5fQTJvpMuS7bq8rYDmyqWjeQ5884LHH7",
  "status": "NoSync",
  "account_id": "test.near",
  "num_peers": 0,
  "is_validator": true,
  "latest_block_hash": "7a4d3SNNb1XGxqhHAKj5nGx8C1R4X8pdt8jobC9z3nup",
  "latest_block_height": 1889,
  "signature": "ed25519:4n5VzXijHUvgwroD1W6BTysRGKTMdPv6ks32kEUNGyb9recDYRpt2L8Y2Uq5ABPt4LZHFBAv2DPj1CAPGkwqkZg2",
  "bandwidth_download": 0,
  "bandwidth_upload": 0,
  "cpu_usage": 0.6015791296958923,
  "memory": 42784
}
```

**Comment by icerove** [comment]
I see #55 has more to display in the UI,do we do all these?

**Comment by frol** [comment]
Let's display all the available information

**Comment by icerove** [comment]
I figure out on localhost, there is no node. So the telemetry api is never called and I could not test whether I wrote it correctly?

**Comment by frol** [comment]
@icerove https://github.com/nearprotocol/near-explorer/pull/139#issuecomment-562551278

**Comment by frol** [comment]
Reopen to address the display items of the issue since #139 only addressed the internal storage.

**Comment by frol** [comment]
Our devnet and betanet are expected to send detailed Telemetry now, so we can display this extended info now (Explorer is unblocked).

**Comment by frol** [comment]
Hey, @corwinharrell! We need your help here to improve the Nodes page (https://explorer.nearprotocol.com/nodes). There is no design there at all, as you can see, and we also have quite some data sitting internally, that we don't display at all, so here is the whole list of data we want to display:

* agent name (currently we have only single nearprotocol implementation and that is "near-rs")
* agent version (e.g. "0.4.5"), and build (e.g. "6a527109-modified")
* node ID ("ed25519:67U1Mup5E98t5fQTJvpMuS7bq8rYDmyqWjeQ5884LHH7")
* node status:
  * Initial state ("AwaitingPeers")
  * Not syncing / Done syncing ("NoSync")
  * Downloading block headers for fast sync ("HeaderSync")
  * State sync, with different states of state sync for different shards ("StateSync")
  * Sync state across all shards is done ("StateSyncDone")
  * Catch up on blocks ("BodySync")
* account ID (e.g. "test.near")
* number of peers (e.g. 0)
* is validator (true/false)
* latest block hash (e.g. "7a4d3SNNb1XGxqhHAKj5nGx8C1R4X8pdt8jobC9z3nup")
* latest block height (e.g. 1889)
* IP address (e.g. 35.228.209.219 or fe80::250:56ff:fec0)

**Comment by kcole16** [comment]
@frol @icerove 
https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=186%3A15 

@frol Do you think the truncated node ID on the far right (`69a3a68...`) is sufficient? 

Also, thinking it makes sense to order the list first by validating/non-validating, then by "Last seen" or latest block height.

**Comment by icerove** [comment]
@kcole16 @frol 
I think it is beautiful. but I need details about some terms. 
the color means it is validator or not?
do we want search box this time and search by what?
I recommend give node ID more digits and we do not have link for node ID now, it seems like a link now.

**Comment by kcole16** [comment]
@icerove Here is a matching of the terms to data: https://www.notion.so/nearprotocol/List-of-Nodes-c71a40417c5048ceb2cb063a0b9f97d0

- Yes, color is indicating validator/non-validator. I think ordering them by validator first, and using a similar tooltip/modal strategy to explain the color can help clarify for users
- IMO we do not need either the search box or the total count on the right side
- The node ID does look like a link. We should instead use black (or gray) instead

**Comment by jakestutzman** [comment]
updated: https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=186%3A15

Do we want to show the full Node ID? It's long, so i'll need to rework it if we do

**Comment by icerove** [comment]
@jakestutzman we do not want to show full node ID, don't worry

**Comment by frol** [comment]
@jakestutzman Your link gives me 404

**Comment by icerove** [comment]
@frol do you have figma?

**Comment by frol** [comment]
I do, and I am signed in

**Comment by icerove** [comment]
@frol  can you open my link?

**Comment by icerove** [comment]
what is this information? 
>node status:

    Initial state ("AwaitingPeers")
    Not syncing / Done syncing ("NoSync")
    Downloading block headers for fast sync ("HeaderSync")
    State sync, with different states of state sync for different shards ("StateSync")
    Sync state across all shards is done ("StateSyncDone")
    Catch up on blocks ("BodySync")
@frol

**Comment by frol** [comment]
@icerove your link is exactly the same as Jake's. Why do you expect it to lead to a different result? No, it is still 404.

The information is the possible values the node status might be.

**Comment by icerove** [comment]
we do not have that information directly, right?

**Comment by icerove** [comment]
I attach screen shot here as you could not open...
<img width="839" alt="image" src="https://user-images.githubusercontent.com/33007476/79512914-5badfc00-7ff7-11ea-8c31-156e6127c4c6.png">

**Comment by frol** [comment]
@icerove 

> we do not have that information directly, right?

```
 "status": "NoSync",
```

nearcore sends that data, we just missed it and never saved. Please, add it to the table and the relevant saving method.

**Comment by frol** [comment]
@jakestutzman I have a concern that the green/grey circle indicators might not be intuitive (well, it is helpful that the legend hint is there, so learned that the green color means that it is a validator), at least I initially thought that it is an online/offline indicator.

**Comment by icerove** [comment]
@jakestutzman 
we have isValidator/notValidator indicator and online/offline indicator, so make this more clear on design is helpful

**Comment by kcole16** [comment]
Maybe green for "online, validating", gray for "online, not validating", and red for "offline"? 

I think ordering by state, and a tooltip could help as well.

**Comment by ilblackdragon** [comment]
Can we separate validators from other nodes somehow?

Also offline nodes can really be hidden is almost never relevant.
Ideally one tab are active validators, another are active non-validators and if we want another one can be non-active (but why would we care?).

Also on the home page it should not be "active nodes/total nodes", it should be "active validator nodes/total active nodes"

**Comment by bowenwang1996** [comment]
Yeah ideally there should be an easy way of viewing all the validating nodes.

**Comment by frol** [comment]
@jakestutzman @kcole16 we need a design for that separation of the validating and non-validating nodes request.

**Comment by jakestutzman** [comment]
@frol @ilblackdragon @bowenwang1996 @kcole16 here's an update. There are two screens here: https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=186%3A15

**Comment by icerove** [comment]
@kcole16 @frol  I want to make sure the definition of active and non-active? Now we only have online and offline, which online is its last_seen is in last minute from now. otherwise it is offline.

**Comment by frol** [comment]
@icerove active === online, non-active === offline

**Comment by bowenwang1996** [comment]
@jakestutzman I got a 404 error on the link.

**Comment by frol** [comment]
@bowenwang1996 I sent you an invite.

@jakestutzman Is it fine to make the design documents available publicly?

**Comment by jakestutzman** [comment]
@frol sorry, i had the settings wrong on this. Everyone who has the link should be able to view now - https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=186%3A15

**Comment by frol** [comment]
@jakestutzman Given @ilblackdragon suggested having two non-overlapping tabs:

> Ideally one tab are active **validators**, another are active **non-validators** and if we want another one can be non-active (but why would we care?).

Do you think we need to have those circle indicators at all given we don't expect to display validator and non-validator nodes on the same page?

**Comment by bowenwang1996** [comment]
@frol from the link that @jakestutzman provided it seems that we use circle indicators to show whether a node is online or not. That is independent of whether a node is a validator.

**Comment by frol** [comment]
@bowenwang1996 If you take a look at the previous version of the design (https://github.com/nearprotocol/near-explorer/issues/128#issuecomment-614930444) you may notice that it was used as a validation status indicator (or at least, it is how I read it). My initial expectation was the same as yours (the circle representing the online/offline status).

@jakestutzman I think we should take this feedback about the circle indicators being confusing. At this point, I am not sure if it ever meant to indicate the validation status or not. Given the conversation, we don't want to display online/offline (active/non-active) status, and neither we do validator/non-validator (given we want to display them in separate tabs).

**Comment by kcole16** [comment]
Given we don't want to show offline nodes right now, we can just remove the circle.

Originally it indicated validator/non-validator, though since we've now split nodes into tabs by validator/non-validator, it is even more intuitive as online/offline. Could bring it back in the future if we want to show offline nodes.

**Comment by icerove** [comment]
@kcole16 I would like to keep the circle thing since we still want the UI. let's just make green one validator and gray one non-validator. We do not show offline validator anymore. the Dashboard one is showing validator/active nodes actually.

**Comment by kcole16** [comment]
> @kcole16 I would like to keep the circle thing since we still want the UI. let's just make green one validator and gray one non-validator. We do not show offline validator anymore. the Dashboard one is showing validator/active nodes actually.

Perhaps to avoid any confusion, we show the green dot for all nodes (validating and non-validating). Keeps it consistent with Dashboard too, and implies all are online.

<img width="259" alt="Screen Shot 2020-04-22 at 11 15 02 AM" src="https://user-images.githubusercontent.com/5624527/80018313-af529680-848a-11ea-949a-e518d0048498.png">
