### ISSUE TITLE
NearKat blocking the support section

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-explorer#131]
## Story

As a user looking at the explorer, and don't get what's going on, I would like to get some help. But "Oh no!" The NearKat is blocking the support section. 
![Screenshot from 2019-11-26 07-54-57](https://user-images.githubusercontent.com/33576047/69606594-876a1e80-1023-11ea-981f-bf6fc2056961.png)

## Acceptance Criteria

- [x] The user can read the support section clearly
- [x] NearKat does not reduce accessibility. (It's a malicious NearKat)

**Comment by icerove** [comment]
fix it in the PR and wait to be merged
