### ISSUE TITLE
Combine actions in a single TX into one line on Transactions page and Dashboard

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#132]
Currently, each action is shown as an individual line in the TX list on the Dashboard and Transactions page, even when multiple actions are part of a single transaction.

**Example**
![](https://yc3.s3.us-east-2.amazonaws.com/Screen+Shot+2019-11-27+at+4.25.45+PM.png)

These three actions are all in the same TX (note the TX hash). The line item should be "Batch Transaction", with an open drawer component containing the three actions.

**[Designs](https://projects.invisionapp.com/share/TCS6KG8G9V7#/screens)**
![](https://yc3.s3.us-east-2.amazonaws.com/Screen+Shot+2019-12-09+at+12.55.59+PM.png)

**Comment by frol** [comment]
It is unclear whether the first action is a good representation of the whole transaction, which is why we went with the flat structure

**Comment by kcole16** [comment]
Hmm, that's a good point. We should find a way to indicate the grouping to the user though. Will see if @jakestutzman has any ideas

**Comment by icerove** [comment]
how about color the transactions in same light color for the same hash to mark these lines are from the same single transaction? Light color for the line not to confuse the content and easy to figure out.

**Comment by kcole16** [comment]
@icerove @frol Updated the issue description with the new designs.

**Comment by kcole16** [comment]
Closed by #147
