### ISSUE TITLE
Update NEAR token units to support yoctoNEAR

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#134]
nearprotocol/nearcore#1723

@frol What do we need to update in Explorer to support this change?

**Comment by frol** [comment]
I believe, it is just a single place: https://github.com/nearprotocol/near-explorer/blob/82b69a20ae7960b26b01b63f7a02acccc7d59599/frontend/src/components/utils/Balance.jsx (in fact, this copy-paste from Wallet should be moved to nearlib as discussed, and in that case we only need to drop this implementations in favor of the nearlib one).

**Comment by icerove** [comment]
I agree with Frol

**Comment by icerove** [comment]
I think for now what we can do is update explorer since writing in nearlib is not happened for now
