### ISSUE TITLE
List of Accounts

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#142]
## Story

As a user, I want to see a list of accounts on NEAR, so I can explore common usage patterns of NEAR and also understand roughly how many unique users there are.

## Acceptance Criteria

- [ ] User can view a list of accounts by selecting the "Accounts" tab in the navbar
- [ ] Each account line item contains the relevant details
  - [ ] Account ID
  - [ ] NEAR balance
  - [ ] Date created
- [ ] Clicking on a account row redirects to the Account Detail page
- [ ] Mobile ok
- [ ] Tested

## Assets

[Designs](https://projects.invisionapp.com/share/TCS6KG8G9V7#/screens/365131593)

**Comment by icerove** [comment]
done
