### ISSUE TITLE
[BUG] Incorrect info on account page

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#154]
When switching from one account to another, the transaction list doesn't update.

# Steps to reproduce

- Open https://explorer.nearprotocol.com/accounts/near
- Click on `@corey` to switch to that page
- Observe that the top panel changed, but not the list of transactions

**Comment by icerove** [comment]
@ilblackdragon  It is not a bug but you should wait for several seconds for that change. I can add a loading icon for that. But it is still okay for now.

**Comment by frol** [comment]
It is definitely a UX bug, so we should add a loader there
