### ISSUE TITLE
The account name is `null` in new access key message

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#159]
## Story

`Access key added for contract: @null`

There is something going wrong as all the messages about new access keys now display "null".

**Comment by kcole16** [comment]
This is actually the case of [Commonwealth](https://commonwealth.im/near/) creating access keys without an associated contract (kinda weird, planning to block on the nearlib and wallet side). 

What we can do is just display `Access key added` when the contract is `null`.

**Comment by frol** [comment]
> What we can do is just display Access key added when the contract is null.

Sounds good to me

**Comment by icerove** [comment]
sounds good.

**Comment by frol** [comment]
I have discussed this issue with Bowen offline and he explained that the `received_id` field is not validated to be an existent account id, and Commonwealth just needed a key which cannot do anything by itself but can be used by them to validate something (e.g. that the user is registered (?)).

```json
"actions": [
    {
        "AddKey": {
             "access_key": {
                 "nonce": 0,
                 "permission": {
                     "FunctionCall": {
                         "allowance": "100000000000000000000",
                         "method_names": [],
                         "receiver_id": "null"
                      }
                }
             },
             "public_key": "ed25519:EWgGz24p4k9DoA16WXkRxv45qv2CWxy7UcZmfY67zqPD"
        }
    }
]
```

Thus, given they just literally put a "null" constant there, there is nothing we can do here.
