### ISSUE TITLE
Contract arguments are displayed broken

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#167]
Here is the example: https://explorer.nearprotocol.com/transactions/5dxrDYuPnrNnMUkZpKfRSHiKsvcAodaziQeoDv2oy971

> Called method: send_message with args {"receiver_id","app_id","message",\"subject\",\"content\"} in contract: @sheeet

On the dashboard and the transactions list it should be in a short form:

> Called method: send_message in contract: @sheeet

and on the transaction details page:

> Called method: send_message in contract: @sheeet
> <pre>{base64-decoded args}</pre>

The main motivation is that the args can get really logs.

NOTE: there is no need to do anything but base64 decoding!

**Comment by kcole16** [comment]
@frol What are your thoughts on @vgrichina idea to use hexdump to parse binary?

"makes sense to do hexdump (e.g. using https://www.npmjs.com/package/hexdump-nodejs) when args cannot be parsed as JSON"

**Comment by frol** [comment]
@k06a that is totally a good idea, let's have a separate issue addressing this.

**Comment by k06a** [comment]
@frol me?

**Comment by frol** [comment]
@k06a oops, sorry :)

@kcole16 ^^^
