### ISSUE TITLE
Dashboard displays default values when loading

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/near-explorer#180]
It seems that the dashboard, when loading, displays 0 for everything including nodes online, block height, tps, etc, which can be confusing especially since it takes several seconds to load.

**Comment by icerove** [comment]
@bowenwang1996  what is default value for these you think? Or you just want "loading" when loading?

**Comment by bowenwang1996** [comment]
I would prefer to see some loading animation when it is loading.

**Comment by icerove** [comment]
make sense
