### ISSUE TITLE
Display fees burnt on Block Details page

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#186]
There are two components of fees that get burnt in every block:
 - State rent: total amount of bytes across all shards * state rent per byte price
 - Tx fees: total amount of gas spent across all shards * gas price in the block

Both of this info can be retrieved from ChunkHeader information within a Block.

We should show:
 - For every block how much burnt fees are there of each type
 - Total fees burnt in the some overall economic stats

**Comment by icerove** [comment]
is this enhancement with #124?

**Comment by frol** [comment]
@icerove it is a similar issue, but that one is about TX Details while this one is about Block Details.

**Comment by bowenwang1996** [comment]
@ilblackdragon I don't see how state rent is easily doable. You want the total state rent instead of what is charged in that block, which requires querying the size of the state in each shard. I am not sure how to do that easily.

**Comment by icerove** [comment]
@ilblackdragon  >State rent: total amount of bytes across all shards * state rent per byte price
also asked @evgenykuzyakov  about this, but it seems that we do not have this available. What we have is the total_rent_paid which is the total rent from beginning to current. It is different as what you want

**Comment by bowenwang1996** [comment]
Actually tx fees is also nontrivial. We only record the gas burnt in the block header for the current block, but to each transaction might have different gas price. Unless we go through all transactions and receipts in the block and trace the original transaction, find the corresponding gas price, and then aggregate all that today, we don't know tx fees for this block.

**Comment by frol** [comment]
@bowenwang1996 why the gas price is different for transactions in the same block? (I know that it might be different for the receipts, but don't understand how this works for transactions)
