### ISSUE TITLE
Refactor Backend

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#205]
### Overview

Redesign and implement a more reliable backend for explorer that can be accessed by external users.

### Requirements

Indexed access to
- Transactions
  - Actions
  - Receipts
- Accounts
  - Mapping of keys to accounts
- Contracts
  - General
  - Matching a specific NEP
- Nodes (validators)
- Chunks
- Blocks

**Comment by frol** [comment]
Closing in favor of #236
