### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/near-explorer#211]
## Story

I got a 500 error for the following transaction:
https://explorer.nearprotocol.com/transactions/EHe5YquDSiEbEcrkVFav21u8brErt9Wpj7PqEvf2nV6p

While near-shell tx-status works:
```
near tx-status EHe5YquDSiEbEcrkVFav21u8brErt9Wpj7PqEvf2nV6p --account_id=eugenethedream
```

**Comment by frol** [comment]
@icerove It seems that some status one that page end up to be an object, and we just pass it to render (for example, `<div>{status}</div>` - this works for string and numbers, but apparently does not work if `status` is an object). Here is the debug message I see running `npm run dev:production-wamp`:

```
found: object with keys {SuccessReceiptId}
```

**Comment by evgenykuzyakov** [comment]
Updated the description with the recent transaction

**Comment by icerove** [comment]
@evgenykuzyakov I see this. It means this receipt success or not? Since it already has `SucessValue`.
@frol also transactions outcome also has this 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/33007476/76264763-ebee6980-621f-11ea-8c5b-96281dbe6f14.png">

**Comment by evgenykuzyakov** [comment]
`SuccessReceiptId` means the result of the receipt depends on the result of the given `receipt_id`.

**Comment by icerove** [comment]
I got SuccessReceiptId means the result depends on the result of the given receipt_id. But it still has problem here. We do not have method to query receipts, do we just show the id here or what do you think? @frol

**Comment by evgenykuzyakov** [comment]
There are `receipts_outcome` array and one of the outcomes is for the given `receipt_id`. You need to recursively follow this path until you arrive at non `SuccessReceiptId` outcome.
