### ISSUE TITLE
Links to tx details don't open in the same page on click

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#214]
1. Go to https://explorer.nearprotocol.com/
2. Click on any Tx hash
Observe that Tx details page didn't open.

To actually open it, need to open in the new tab.

This is especially weird on mobile.

**Comment by icerove** [comment]
@ilblackdragon  it can open but really really slow

**Comment by frol** [comment]
It is an issue of rps limits to nearcore RPC. We should investigate the performance issues on nearcore side first, and also reduce the number of RPC calls by exposing transaction status in the chunks API: https://github.com/nearprotocol/nearcore/issues/1880
