### ISSUE TITLE
Move actions into a separate SQL table 

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#217]
Move Actions into their own table from the Transactions table

**Comment by frol** [comment]
As discussed with @icerove, the new table should have at least the following columns:

* `transaction_hash` [part of a compound primary key]
* `action_index` (simple integer indicating the index of the item in the original array of actions in the transaction, so starts with 0, 1, 2, ...) [part of a compound primary key]
* `action_type` (string):
  * `CreateAccount`
  * `DeployContract`
  * `FunctionCall`
  * `Transfer`
  * `Stake`
  * `AddKey`
  * `DeleteKey`
  * `DeleteAccount`

  nearcore sources for reference: https://github.com/nearprotocol/nearcore/blob/697d15debabcb69c6bea286329f0aa0d2a8e7284/core/primitives/src/transaction.rs#L46-L58
* `action_args` (JSON string) -- consider having some data extracted into columns (I don't see a point right now, but I may miss something here).
