### ISSUE TITLE
Test loads, profile query performance

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#219]

**Comment by frol** [comment]
Let's address #217 first.

**Comment by frol** [comment]
We want to test 10k, 100k, 1m, 10m, ... blocks, transactions, actions, and see what is the limit we can handle. To do that, generate fake data into your local backend database and measure the execution time of the common SQL queries we have (either extract them from the frontend source code, or use DevTools in the browser to see what SQL queries are sent from the frontend).

Testing scenarios:

1. Empty blockchain: only blocks and chunks are in the system (no transactions and actions)
2. Every block has 1 chunk and 10 transactions (1-3 actions each)
3. Every block hash 10 chunks and 1000k transactions (1-3 actions each)

Please, report your testing environment (CPU type, RAM, OS), and the table of results for various checkpoints which you find important (e.g. 1 block and 1 transaction is the baseline performance, 1m blocks we start to experience a minor slowdown of 10ms latency, etc) with the execution time of various queries + the DB file size.

**Comment by frol** [comment]
@bowenwang1996 I did, fixed :+1:

**Comment by icerove** [comment]
https://docs.google.com/spreadsheets/d/1jfn6EGTUXKXY5xKl7R9YrrAFAhjHmMHcuzLTpZ5CiVQ/edit#gid=0

**Comment by icerove** [comment]
https://docs.google.com/spreadsheets/d/1jfn6EGTUXKXY5xKl7R9YrrAFAhjHmMHcuzLTpZ5CiVQ/edit?usp=sharing

**Comment by frol** [comment]
@icerove Great job!

The benchmarks show the expected picture for the old DB structure, that is, we cannot handle even 100k transactions in a timely manner.

As per our offline discussion, we want to update the benchmark as of PR #231. It is great that we have this baseline benchmark to see if it is going to be any better now.

**Comment by icerove** [comment]
@frol with indices, the SQL queries (especially query for 15 transactions) do not change its query time (less than 100 milliseconds) while DB size increasing and blocks number increasement. So it should be guaranteed the SQLite backend will not be the limit for query.

**Comment by icerove** [comment]
I also notice that when block contains 1k tx, the maximum block number for render.com we have now is about 22500 blocks since it will be 15GB.

**Comment by icerove** [comment]
we can have 2m blocks which contains 10 txs in each to hit the ceiling on render disk 15GB.

**Comment by frol** [comment]
> with indices, the SQL queries (especially query for 15 transactions) do not change its query time (less than 100 milliseconds)

I want to clarify that having the indices the query execution time is always under 100 milliseconds no matter how many transactions are in the database (100k / 1m / 10m / ...). Am I reading this right?

> I also notice that when block contains 1k tx, the maximum block number for render.com we have now is about 22500 blocks since it will be 15GB.

The storage is not a problem so far, we can increase the storage without even rebooting the service. I have already done that a couple of times bumping from 10GB to 12GB and today I bumped it to 15GB. Also, with the new testnet, we should have 1 shard instead of 8, which means that we will have 8 times fewer chunks, and that is by far is the biggest part of the DB (I even considered disabling syncing chunks).

**Comment by icerove** [comment]
>I want to clarify that having the indices the query execution time is always under 100 milliseconds no matter how many transactions are in the database (100k / 1m / 10m / ...). Am I reading this right?

correct and I think of the reason is it is just like query one specific row with indices indicator like hash. when it find out the first one, it already get the whole rows.

**Comment by icerove** [comment]
>I even considered disabling syncing chunks
I totally agree with this now.

**Comment by frol** [comment]
Well, to sum it up:

The queries' performance is great. We also confirmed this with devnet, where we generated 7.6 million transactions in 40k blocks in a single day.
