### ISSUE TITLE
Confusing "Value" on Transaction Details page

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#233]
## Story

As a user, I want to know what I am looking at so I don't get confused.

"Value" term is quite overloaded (at least, among tech people).

![image](https://user-images.githubusercontent.com/304265/77694387-b15b2f80-6f88-11ea-885e-ffe8a01108bf.png)

Spoiler alert! (test yourself if you understood the term correctly in this context)

> Value is a sum of all NEAR tokens for transfer (i.e. `Transfer` action(s)).

It is related to #201 /cc @kcole16 

## Acceptance Criteria

- [ ] Discuss and find a better term or way to present this information to a user (maybe we can just have a hint in the UI helping users to better understand the values)
- [ ] Implement the fix
- [ ] Mobile ok
- [ ] Tested

**Comment by kcole16** [comment]
We currently use a clickable icon "i" and modal to display additional information about Top Level Accounts on the wallet. 

This could be useful to provide further details about "Value" in Explorer, and eventually every row in the accounts table.
<img width="127" alt="Screen Shot 2020-04-13 at 11 31 52 AM" src="https://user-images.githubusercontent.com/5624527/79148719-d28a9100-7d7a-11ea-96d8-d1d6d95fb0f9.png">
<img width="350" alt="Screen Shot 2020-04-13 at 11 32 01 AM" src="https://user-images.githubusercontent.com/5624527/79148733-d7e7db80-7d7a-11ea-8e90-605d193bf10e.png">



> Value is the sum of all NEAR tokens transferred from the Signing account to the Receiver accou t. This includes tokens sent in a Transfer action(s), and as deposits on Function Call action(s).

**Comment by kcole16** [comment]
The above actually fits pretty well in #237

**Comment by kcole16** [comment]
This is being addressed in #237
