### ISSUE TITLE
UI should help people to learn core concepts

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#237]
## Story

As a regular user who just started learning about NEAR, I want to know what I am looking at so I can build my understanding of the system.

Currently, most of the numbers in our UI are quite unintuitive (including NEAR, Gas, number of nodes, block height).

There already have been a few questions about what Tgas is (that is Teragas, which is 10^12 gas).

I believe we should have hints with short explanations and links to the documentation.

## Acceptance Criteria

- [x] Each term in the Detail page tables has a tooltip/modal with explanation
  - [x] Account Detail
  - [x] Transaction Detail
  - [x] Block Detail
  - [x] Dashboard
- [x] Mobile ok
- [ ] Tested

## Notes

List of terms and explanations: https://docs.google.com/spreadsheets/d/1-4-zKSvf_v68AGFFmTgoKoGxtRXLW5dL7L7wMEdAdZg/edit#gid=0

**Comment by frol** [comment]
Blocked on DevX decision: https://github.com/near/devx/issues/118

**Comment by kcole16** [comment]
Action Items:
- [ ] Create a list of terms (table headers in Dashboard, Account Detail, TX Detail, Block Detail)
- [ ] Sync with @amgando on potential descriptions, links to docs for terms
- [ ] Implement similar to Wallet

<img width="127" alt="Screen Shot 2020-04-13 at 11 31 52 AM" src="https://user-images.githubusercontent.com/5624527/79148719-d28a9100-7d7a-11ea-96d8-d1d6d95fb0f9.png">
<img width="350" alt="Screen Shot 2020-04-13 at 11 32 01 AM" src="https://user-images.githubusercontent.com/5624527/79148733-d7e7db80-7d7a-11ea-8e90-605d193bf10e.png">

> Value is the sum of all NEAR tokens transferred from the Signing account to the Receiver accou t. This includes tokens sent in a Transfer action(s), and as deposits on Function Call action(s).

**Comment by kcole16** [comment]
@amgando If you get a chance, would love your feedback here: https://docs.google.com/spreadsheets/d/1-4-zKSvf_v68AGFFmTgoKoGxtRXLW5dL7L7wMEdAdZg/edit#gid=0

This is a list of terms we want to explain in the Explorer UI. I've added a rough draft of descriptions for each.

**Comment by icerove** [comment]
#232
