### ISSUE TITLE
Transactions list fails to load the next page on betanet

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#260]
I don't know what is the problem, but for some reason, the transactions page on the betanet cannot load the transactions beyond the initial page: https://explorer.betanet.nearprotocol.com/transactions

## Acceptance Criteria

- [ ] The scroll pagination shows the next transactions

**Comment by icerove** [comment]
I see the error message as this on local backend:
<img width="972" alt="image" src="https://user-images.githubusercontent.com/33007476/79893413-e6587780-83b8-11ea-8bb7-feb0354eaff2.png">

**Comment by icerove** [comment]
here is my local DB data:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/33007476/79895295-83b4ab00-83bb-11ea-81cc-e1b30984f7e9.png">

**Comment by icerove** [comment]
Here is the blockTimestamp bug: 
<img width="828" alt="image" src="https://user-images.githubusercontent.com/33007476/79903279-a64cc100-83c7-11ea-875f-edd4fa52a628.png">

The timestamp is not sequencely inserted in the database and when the following block timestamp is larger than the previous, we could not fetch.

**Comment by icerove** [comment]
This happens when we regularSyncNewNearcoreState and regularSyncMissingNearcoreState at the same time not waiting fetch old state then adding the new state. We do not control the insert sequence and thus timestamp maybe not a correct indicator for the pagination any more.

**Comment by frol** [comment]
> This happens when we regularSyncNewNearcoreState and regularSyncMissingNearcoreState at the same time not waiting fetch old state then adding the new state. 

Yeah, the collision is possible given the huge blocks with hundreds of transactions, but why does it arrive into an inconsistent state where the transactions are saved, but not the blocks? :thinking: 

> timestamp maybe not a correct indicator for the pagination any more.

Why? The timestamp should be assigned based on the block timestamp and has nothing to do with the real time and the insert order, has it?

**Comment by frol** [comment]
I believe this should not have been possible to happen since we commit changes into SQLite as a single DB transaction, which includes the blocks, their relevant chunks, and their relevant transactions (+ accounts and access keys), so there should be no way we have the transactions saved in the database without the corresponding blocks.

I am closing this issue as we cannot reproduce it now, and the action item should be #263.
