### ISSUE TITLE
Display balance + locked amount on the Accounts List page

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#264]
## Story

As a regular user who opens the page of a list of accounts, I want to see the total amount of tokens belongs to the account has. Otherwise, it is counter-intuitive and causes major confusion.

## Acceptance Criteria

- [x] The amount displayed on the Accounts List page is a sum of balance + locked
- [x] Unit-tested

**Comment by icerove** [comment]
I am confused about this, our amount showing on the list page is already the amount query from query-account RPC and it is total amount user have. 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/33007476/80246637-97614b00-8621-11ea-90a0-08e4b82f7cc0.png">
see this said balance is included the locked token.
@frol

**Comment by frol** [comment]
@icerove the value does not match the description. We currently display the `amount` returned from the RPC as the balance, and it is the "spendable balance", and we don't include "Locked".

@kcole16 @bowenwang1996 Does wallet include the locked balance? I would find it confusing as I cannot transfer the locked tokens. On the second thought, I do NOT think that displaying the spendable balance + locked as a single value makes sense.

**Comment by kcole16** [comment]
@frol We're planning to show the total balance on the Wallet dashboard and Navbar, a complete breakdown on the Profile page, and the available balance (with an "info" icon and explanation) on the TX signing page.

**Comment by icerove** [comment]
@kcole16 cool!
We should have a clear thing here: the amount from account querying from rpc is the total number of token or spendable amount, the total should be the amount + locked token?

**Comment by frol** [comment]
@icerove RPC returns `amount` (a spendable amount) and `locked`, so to get the total we sum them up.
