### ISSUE TITLE
Fix formatting for AddKey transactions

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#32]
@ilblackdragon Do we need to filter the information to shrink it down or should we just make sure that there is no overflow?

![image](https://user-images.githubusercontent.com/304265/61517607-5728c880-aa10-11e9-878a-fdfe17161e47.png)

**Comment by ilblackdragon** [comment]
We need not to show JSON for starters.
Instead show "AddKey", details if this is an access key (e.g. contract it's an access key for), otherwise just show base58 of the public key added.

**Comment by robin-thomas** [comment]
@ilblackdragon Just to confirm, if there is an `access_key`, display just the `conntract_id`. If not, display the `new_key`?

**Comment by vgrichina** [comment]
It might be also good time to plug in some templating / localization. We'll need to have non-JSON descriptions for stuff like method calls too, so we might do it something like:
1. Lookup template string for given transaction type (if it's method call – looked up in contract metadata).
2. Use some simple logic-less templating (e.g. https://github.com/janl/mustache.js/) to render final result.

So e.g. for adding a key template can be something like `Add {{new_key}} as a public key`

**Comment by robin-thomas** [comment]
@vgrichina Good idea. I'll check out the templating.

Also how to get a human-readable public key? In the JSON, it's an array of digits. Is it some bytes form?

**Comment by frol** [comment]
@vgrichina @robin-thomas What benefits does mustache provide over React in terms of templating? Why cannot we just create separate components for each transaction type? I agree that we might need localization, but we already do templating with React, I don't understand the benefits of another templating engine here.
