### ISSUE TITLE
Block details are empty page

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#34]
Here is an example of block page that is just empty:
https://near-explorer-frontend.onrender.com/blocks/HX4VrkKpkis6KNV9uLjTQjt1JtQxkjUT39qDqqRpQomw

**Comment by robin-thomas** [comment]
As you can see here: https://near-explorer-frontend.onrender.com/blocks/4m4pTEvo5hzZMYonhPsauunRJLKW1trB9XJTiNuR66on it's fixed by pr 35.
