### ISSUE TITLE
Node details report

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#55]
Clicking on nodes on dashboard should lead to page with table of currently reported telemetry nodes. With columns like:
```
     AccountId           |     Location   |       IP Address    |      Version     | CPU | Memory | Peer count | Last height     |    
 (can be empty)
```

**Comment by frol** [comment]
It is currently blocked by #54. I am working on resolving the issue of missing telemetry at the moment.

**Comment by frol** [comment]
It is unblocked now since you can add new nodes manually:

```
$ curl -i -X POST -d 'node_id=frol' -d 'account_id=frol' -d 'latest_block_height=1' https://explorer.nearprotocol.com/api/nodes
```

**Comment by frol** [comment]
The telemetry is now working fine, so this issue is unblocked.

**Comment by icerove** [comment]
same with #128
