### ISSUE TITLE
TX List: Search and pagination

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#61]
We already have this for blocks, so we should also have this for transactions.

**Comment by kcole16** [comment]
### Acceptance Criteria

- [ ] TXs are paginated on `/transactions` list page
- [ ] TXs are paginated on individual account pages e.g. `/accounts/test`
- [ ] User can view all TXs for an account

@icerove

**Comment by frol** [comment]
Quick hint for the implementation: it seems that we need an integer column or even two on the transactions table on the Explorer backend that would be used to do offset and limit (block height is what we have in blocks, so for transactions, we may want to have a block height and (chunk id * 100000 + transaction index in a given block)).
