### ISSUE TITLE
Setup tests / CI infrastructure for frontend

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-explorer#63]

**Comment by deacix** [comment]
Hey! Which CI? CircleCI? Travis?

**Comment by frol** [comment]
@deacix I would like to give GitHub Actions a try: https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by deacix** [comment]
Can you provide rights to me for this repo? So I can setup the ci?

**Comment by deacix** [comment]
Some docs from Github:
 - https://help.github.com/en/articles/configuring-a-workflow
 - https://help.github.com/en/articles/workflow-syntax-for-github-actions

**Comment by deacix** [comment]
please close the story
