### ISSUE TITLE
Port to TypeScript

### ISSUE THREAD

**Issue by deacix** [nearprotocol/near-explorer#84]
The whole code should be ported to TypeScript to improve on boarding new users and have better code handling.

**Comment by deacix** [comment]
After some hours of analyzing is my suggestion is to move to Angular. You will get great toolset and a stable environment for your app instead of putting different libs and configs together..

**Comment by frol** [comment]
What kind of configs do you refer to? Next.js provides TS environment out of the box (just name a file with ts or tsx extension). I just couldn’t find a use for TS in the React (frontend) app. On the backend side there is no framework at all, it is a plain Node.js application, so I just didn’t want spend my time setting up TS there.

**Comment by deacix** [comment]
can you ping me in telegram: @deacix
