### ISSUE TITLE
Implement Continues Deployment to staging env

### ISSUE THREAD

**Issue by deacix** [nearprotocol/near-explorer#94]
## Story

As a developer who is building the near-explorer, I want to have continues deployment of latest version so I can test it on staging environment.

## Acceptance Criteria

- [ ] Deployment environment is defined
- [ ] Deployment is setup in Github Actions
- [ ] After every commit in the staging branch (should be defined) the latest version is deployed and usable 
- [ ] CD is tested

**Comment by frol** [comment]
CD is set up (just as the production deployment) on Render.com. The link is automatically published via a comment to a PR. The deployment environment is defined with the Dockerfile (so you can build the same environment on a local machine)
