### ISSUE TITLE
Exact Search for TX, Account, Block

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#99]
## Story

As a user, I want to be able to search for a transaction by it's hash, an account by name, and a block by block number, so I can view the details of the TX/account/block to debug without interpreting the URL schema or finding a link.

## Acceptance Criteria

- [x] User can search by TX hash
- [x] User can search by account name
- [x] User can search by block hash
- [x] User can search by block height
- [x] User is redirected if a match is found
- [x] User receives a message "Result not found" if no match
- [ ] Tested

## Assets

- [Designs](https://app.zeplin.io/project/5c6f069601b1361ba39eaee7/screen/5c6f0a977372fb3306dd0211)

**Comment by kcole16** [comment]
@deacix Added the designs for this (in Zeplin)

**Comment by kcole16** [comment]
@icerove Adding you to this issue as well. Just needs an enhancement:

Currently, you can search by block hash, whereas we expect the user to search by block number (since they are more likely to have that)

**Comment by bowenwang1996** [comment]
@kcole16 there is not a one-to-one mapping between block height and block, especially for recent blocks.

**Comment by kcole16** [comment]
@bowenwang1996 Interesting, is there ever a guaranteed one-to-one mapping, or should we just keep search to block hash?

**Comment by bowenwang1996** [comment]
For finalized blocks yes we can say that the mapping from blocks to heights is injective, but still not surjective though. In other words, for some height, there might not exist a corresponding block.

**Comment by icerove** [comment]
So do we still want to add the function to search from block height? @kcole16

**Comment by kcole16** [comment]
@icerove Yes, let's add block height in addition to block hash, so users can search by either
